name: 'Minify-JS Action'
description: 'Github action to minify html, javascript and css files'

runs:
  using: 'composite'
  steps:
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.32.0
    - uses: ./minify

branding:
  icon: "box"
  color: "green"
